services:
  # Alpha Date Automation Service
  # This service handles authentication with Alpha.Date using both Puppeteer and API methods
  # If Puppeteer fails (Chrome not available), it falls back to API authentication
  - type: web
    name: alpha-date-automation
    runtime: node
    buildCommand: npm run build:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_ZENROWS
        value: "false"
      - key: ZENROWS_API_KEY
        value: "a99283cb465506ebb89875eeff4df36020d71c7b"