services:
  - type: web
    name: alpha-date-automation
    runtime: node
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
      echo "Chrome installed at: $(npx puppeteer browsers list)"
      npm run debug:chrome
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome-linux/chrome