services:
  # Alpha Date Automation Service
  # This service handles authentication with Alpha.Date using both Puppeteer and API methods
  # If Puppeteer fails (Chrome not available), it falls back to API authentication
  - type: web
    name: alpha-date-automation
    runtime: node
    buildCommand: npm run build:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-127.0.6533.88/chrome-linux64/chrome
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_DISABLE_HEADLESS_WARNING
        value: "true"
      - key: PUPPETEER_ARGS
        value: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-gpu"
      - key: USE_ZENROWS
        value: "true"
      - key: ZENROWS_API_KEY
        value: "a99283cb465506ebb89875eeff4df36020d71c7b"